name: my_huski
description: "My Huski"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  font_awesome_flutter:
  google_fonts:
  huski_backend:
    path: ../backend
  huski_common:
    path: ../common
  intl:
  provider: ^6.0.0
  http: ^0.13.3
  infinite_scroll_pagination: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true